### ISSUE TITLE
Searching for the components on the internet then on ground .

### ISSUE THREAD

**Issue by ayamostafa285** [menna-hussien/ASUMobiCarG55#8]
first task which is searching for the best component and buying it in real .

**Comment by ayamostafa285** [comment]
@erwaaa @AsmaaMohamed12 @ayagamilali

**Comment by erwaaa** [comment]
we used arduino uno in our first test but we found a trouble with the number of pins so we tried to use arduino mega ,, we found another trouble in coding the mega one so we are waiting to buy the uno within 2 days at most to continue the testing

**Comment by AsmaaMohamed12** [comment]
We bought Arduino Mega
